version: 0.2

phases:
  pre_build:
    commands:
      - cd my-first-nuxt-app
      - npm install
      - npm install -g contentful-cli
      - npm run import-data -- --space-id o0otsmrrpq9r --management-token CFPAT-tg4zcR_Rl0-sfZfO6Jcj4ztQYqN3vsexyDqLP5Q0-70
      - contentful login --management-token CFPAT-tg4zcR_Rl0-sfZfO6Jcj4ztQYqN3vsexyDqLP5Q0-70
  build:
    commands:
      - npm run generate
artifacts:
  files:
    - 'my-first-nuxt-app/dist/**/*'
  base-directory: dist
