version: 0.2

phases:
  pre_build:
    commands:
      - npm i -g yarn
      - npm i -g @vue/cli @vue/cli-init
      - cd my-first-nuxt-app
      - yarn
  build:
    commands:
      - yarn run generate
artifacts:
  files:
    - 'dist/**/*'